### ISSUE TITLE
Nevarne SQL poizvedbe

### ISSUE THREAD

**Issue by jaanos** [rdeca/Dietetika#1]
Opažam, da imata tukaj dve nevarni SQL poizvedbi:

https://github.com/rdeca/Dietetika/blob/be470aadf534b62ba2ad3dd748409f60f4bc0885/app/app.py#L54-L77

Tako vstavljanje podatkov s pomočjo `format` lahko vodi do napadov [SQL](https://en.wikipedia.org/wiki/SQL_injection) [injection](https://xkcd.com/327/). Namesto tega uporabita vprašaje, tako kot drugod v kodi.

**Comment by alesbrelih** [comment]
Hvala.
Malček izven konteksta, vendar ali obstajajo named parametri pri poizvedbah v pythonu?

**Comment by jaanos** [comment]
`sqlite3` [podpira](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.execute) poimenovane parametre.

Vidim, da je tole rešeno, tako da zapiram. Seveda lahko issue tudi sama zapreta s klikom na **Close issue** (ali **Close and comment**, če ob tem še kaj napišeta). Issueje lahko zapirata tudi s commiti - če v sporočilo ob commitu napišeta *Closes #1* (kjer je #1 številka issueja), potem se bo issue zaprl, ko bosta commit objavila na GitHubu.
